Vagrant.configure(2) do |config|
    # Shuffler location
    config.vm.synced_folder "./", "/vagrant"

    # VM for Sequencer
    (12..16).each do |i|
      config.vm.define "bank-server-#{i}" do |cfg|
        # VM box
        cfg.vm.box = "hashicorp/bionic64"
        cfg.vm.box_version = "1.0.282"
        # Network configuration
        cfg.vm.network "private_network", ip: "10.0.1.1#{i}"
        # Provision a Python environment
        cfg.vm.provision "shell", inline: <<-SHELL
          # Install tools
          sudo apt-get update
          sudo apt-get -y install python-pip
          sudo apt-get -y autoremove
          # Install app dependencies
          cd /vagrant
          sudo pip install -r requirements.txt
          # Run server
          python server.py
        SHELL
      end
    end

end