# -*- mode: ruby -*- 
# vi: set ft=ruby : 

# Every Vagrant development environment requires a box. You can search for 
# boxes at https://atlas.hashicorp.com/search. 
BOX_IMAGE = "hashicorp/bionic64" 
BOX_VER = "1.0.282"
NODE_COUNT = 3 

Vagrant.configure(2) do |config|

  # Shuffler location
  config.vm.synced_folder "./", "/vagrant"

  # Master machine
  config.vm.define "bank-server-master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VER
    subconfig.vm.network :private_network, ip: "10.0.1.12"
  end

  # Bank server machines
  (1..NODE_COUNT).each do |i|
    config.vm.define "bank-server-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VER
      subconfig.vm.network :private_network, ip: "10.0.1.#{i + 12}"
    end
  end

  # Provision a Python environment
  config.vm.provision "shell", inline: <<-SHELL
    # Install tools
    sudo apt-get update
    sudo apt-get -y install python-pip
    sudo apt-get -y autoremove
    # Install app dependencies
    cd /vagrant
    sudo pip install -r requirements.txt
    # Run server
    nohup python server.py &
  SHELL

end